### ISSUE TITLE
Regexp characters are not escaped for insertion into string

### ISSUE THREAD

**Issue by robrix** [maxbrunsfeld/node-tree-sitter-compiler#1]
e.g.:

```javascript
/"\{\}"/
```

1. This does not get escaped correctly, so the `"`s both end the string.
2. After correcting for that, `\` does not get escaped correctly, so the compiler complains about the unknown escape sequence `\{`.

**Comment by maxbrunsfeld** [comment]
Whoops! I think this is fixed in 0.0.32.

**Comment by robrix** [comment]
It is indeed! :bow:
