### ISSUE TITLE
Unicode code points are ignored in regexps

### ISSUE THREAD

**Issue by robrix** [maxbrunsfeld/node-tree-sitter-compiler#2]
```javascript
/[^\u000a]/
```

There is some overlap with #1 here in that the `\` does not get escaped, and the C compiler complains about the unicode character referenced being a control character. Correcting for this (by prepending another backslash to escape it for the C compiler but leave it present for the regexp handling), the code point is apparently ignored—it won’t match `a string` because of the `a`.

**Comment by maxbrunsfeld** [comment]
I think this is fixed in 0.0.33.

**Comment by robrix** [comment]
It is! :bow:
